### ISSUE TITLE
No manual available yet, correct?

### ISSUE THREAD

**Issue by jk86754** [aristoteleo/Scribe-py#2]
![image](https://user-images.githubusercontent.com/11413558/76090408-85501e00-5f89-11ea-9fac-e22a72e68530.png)

**Comment by Xiaojieqiu** [comment]
Hi @jk86754 thanks, I have not work on the manual yet (mostly because I graduated from Cole's lab and started new projects for my post-doc career). But I will do it in a few days. Please note that you can check some notebooks from here: 
https://github.com/aristoteleo/Scribe-Python-notebooks

Also, we have an R package too: 
https://github.com/aristoteleo/Scribe

Finally, I am developing dynamo on the side which aspires to dramatically go beyond  RNA velocity to learn transcriptomic vector fields to predict long time cell fate. You may find dynamo interesting:
https://github.com/aristoteleo/dynamo-release

Scribe can be used with dynamo and further integration is  in the process
